* IB CS genetic algorithm case study program
** The purpose of this repository
   This repository contains a program implementing a genetic algorithm
   to find a solution to the travelling salesman problem (TSP). TSP
   data is taken from IBO CS genetic algorithm case study.

   The current version supports 
   - truncation and roulette wheel selection (see file =Main.java=)
   - PMX crossover
   - city-switch mutation. 
   The algorithm terminates if there is no improvement in the fittest
   individual and no improvement in \ldquo{}median\rdquo fitness from
   previous generation.

** Usage
   For basic usage, just compile and run the program (see below). All
   program data and parameters are coded in.

   To explore the role of parameters -- such as population size,
   number of elites, or mutation rate -- change corresponding values
   in class =Main=.

   To explore alternative methods of, for example, crossover,
   implement a corresponding subclass of the abstract base class,
   construct it in =Main=, and pass it to class =TSPGeneticAlgorithm=.

** Measure of fitness
   Genetic algorithms maximize fitness. In TSP, route length is
   minimized. So route length can not be used as a direct measure of
   fitness.

   In this implementation, the measure of fitness is the /negative/ of
   route length. When this is maximized, route length is
   minimized. This measure allows the user to immediately see the
   corresponding route length from a fitness value.

** Installation in IDEA
   To install the application in IDEA, do the following:
   1. Clone the repository.
   2. Right click on class =Main=.
   3. Select =Run Main.main()=
   You are now able to make changes to the project and run it again.

** Alternative installation method
   1. Clone repository.
   2. Run =ant= default target (builds and runs the application).
   
** License
   Copyright (C) 2021 Jarmo Hurri and Askar Tuiushev

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
